name: google_signin_example
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #Firebase
  cloud_firestore: ^1.0.1
  get_it: ^6.0.0
  firebase_core: ^1.0.1

  # google sign in
  #firebase_auth: ^0.18.3
  firebase_auth: ^1.0.1
  google_sign_in: ^4.5.6

  # state management
  provider: ^4.3.2+2

  # icon of google
  font_awesome_flutter: ^8.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
